---

title: 'StevenCombs.com'
logo: '/images/design/steven-square.svg'
description: 'Blog posts and video from Steven as he “COMBS” through the minutia to discover tech, retro-computing, physical computing, gadgets and sci-fi.'
google_analytics: UA-1632774-9
name: 'Steven B. Combs'
email: 'steven.combs@gmail.com'
tagline: 'Combsing through the minutia…'
url: 'https://www.stevencombs.com'

lsi: false
comments: true
highlighter: rouge
 linenos: true

themed:
 highlight_color: '#3498db'
 show_disclaimer: true

tipue_search:
  include:
    pages: true

exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - .DS*
