---

name: "Steven Combs"
description: "Steven Combsâ€™ Blog"
tagline: "Combsing through the minutia"
url: "http://www.stevencombs.com"

exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
lsi: false
comments: true
highlighter: rouge
theme: jekyll-theme-minimal

themed:
  email: steven.combs@gmail.com
  google_analytics_key: UA-1632774-9
  highlight_color: "#3498db"
  name: "Steven Combs"
  show_disclaimer: true
  social:
    gplus: +StevenCombsPhD
    linkedin: stevencombs
    twitter: StevenCombs
    github: stevencombs
    tumblr: stevencombs
    facebook: steven.b.combs
